src/Edi.LightBlog/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Edi.LightBlog.Core;
using Edi.LightBlog.Core.Data;
using Edi.LightBlog.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace Edi.LightBlog.Controllers
{
    public class AboutController : ControllerBase
    {
        private IHttpContextAccessor _accessor;

        public AboutController(ILogger<AboutController> logger,
            IOptions<AppSettings> settings,
            IConfiguration configuration,
            IHttpContextAccessor accessor)
            : base(logger, settings, configuration)
        {
            _accessor = accessor;
        }

        public async Task<IActionResult> Index()
        {
            var dataDir = AppDomain.CurrentDomain.GetData("DataDirectory") as string;
            var mdFilePath = Path.Combine(dataDir, "About.md");
            if (System.IO.File.Exists(mdFilePath))
            {
                _logger.LogInformation($"Reading file: {mdFilePath}");

                var mdContent = await System.IO.File.ReadAllTextAsync(mdFilePath);
                var htmlContent = CommonMark.CommonMarkConverter.Convert(mdContent);
                var model = new AboutModel() { PageContent = htmlContent };
                return View(model);
            }
            return NotFound();
        }
    }
}

src/Edi.LightBlog/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Edi.LightBlog.Core;
using Edi.LightBlog.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace Edi.LightBlog.Controllers
{
    [Authorize]
    [AutoValidateAntiforgeryToken]
    public class AdminController : ControllerBase
    {
        public AdminController(ILogger<AccountController> logger,
            IOptions<AppSettings> settings)
            : base(logger, settings)
        {
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult UpdateConfiguration(AppSettingsViewModel model)
        {
            if (ModelState.IsValid)
            {
                ViewBag.Message = "Configuration Updated.";
                return RedirectToAction(nameof(Index));
            }

            return View("Index");
        }
    }
}

src/Edi.LightBlog/Views/Shared/_AdminMenu.cshtml
@{
    var currentController = ViewContext.RouteData.Values["controller"].ToString();
    string currentAction = ViewContext.RouteData.Values["action"].ToString();
}

<h2 class="page-header">Blog Admin</h2>

<ul class="nav nav-tabs">
    <li role="presentation" class="@(currentAction == "Index" ? "active" : null)">
        <a asp-action="Index" asp-controller="Admin">Dashboard</a>
    </li>
    <li role="presentation" class="@(currentController == "Post" ? "active" : null)">
        <a asp-action="Manage" asp-controller="Post">Posts</a>
    </li>
    <li role="presentation" class="@(currentController == "Comments" ? "active" : null)">
        <a asp-action="Manage" asp-controller="Comments">Comments</a>
    </li>
    <li role="presentation" class="@(currentController == "Category" ? "active" : null)">
        <a asp-action="Manage" asp-controller="Category">Categories</a>
    </li>
    <li role="presentation" class="@(currentController == "Tags" ? "active" : null)">
        <a asp-action="Manage" asp-controller="Tags">Tags</a>
    </li>
</ul>

<div class="bor-10"></div>

src/Edi.LightBlog/Views/Shared/_Layout.cshtml
@using Edi.LightBlog.Core
@using Microsoft.AspNetCore.Authentication

@using Microsoft.Extensions.Options;
@inject IOptions<AppSettings> Settings
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@inject IAppInfomation AppInfomation

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    @RenderSection("meta", required: false)
    <title>@Settings.Value.Title @ViewData["Title"]</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link href="~/lib/font-awesome/css/font-awesome.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link href="~/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("head", required: false)
    @RenderSection("Scripts", required: false)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Post" asp-action="Index" class="navbar-brand">@Settings.Value.Title</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Post" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Category" asp-action="Index">Categories</a></li>
                    <li><a asp-area="" asp-controller="Tags" asp-action="Index">Tags</a></li>
                    <li><a asp-area="" asp-controller="About" asp-action="Index">About</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">@User.Identity.Name <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a asp-area="" asp-controller="Admin" asp-action="Index">Dashboard</a></li>
                                <li><a asp-area="" asp-controller="Account" asp-action="SignOut">Sign Out</a></li>
                            </ul>
                        </li>
                    }
                    else
                    {
                        <li><a asp-area="" asp-controller="Account" asp-action="SignIn">Sign In</a></li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        @RenderBody()
    </div>

    <footer>
        <hr />
        <div class="container">
            <div class="row">
                <div class="col-md-7">
                    <p class="p-copyright">
                        &copy; @DateTime.UtcNow.Year @Settings.Value.Copyright
                    </p>
                </div>
                <div class="col-md-5">
                    <p class="p-appinfo text-muted">
                        V @AppInfomation.GetAppVersion() <br/>
                        Powered by <a href="https://github.com/EdiWang/Edi.LightBlog" target="_blank">Edi.LightBlog</a> with <a href="http://dot.net" target="_blank">ASP.NET Core 2.0</a>
                    </p>
                </div>
            </div>
           
           
            <div class="bor-10"></div>
        </div>
    </footer>
</body>
</html>